import { Navbar } from '@/components/Navbar'
import { DarkModeProvider } from './providers/DarkModeProvider'
import './globals.css'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html suppressHydrationWarning lang="en">
            <body className="bg-dark-50 dark:bg-dark-950">
                <DarkModeProvider>
                    <Navbar />
                    {children}
                </DarkModeProvider>
            </body>
        </html>
    )
}
