import { Navbar } from '@/components/Navbar'
import './globals.css'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="dark">
            <body className="bg-dark-50 dark:bg-dark-950">
                <Navbar />
                {children}
            </body>
        </html>
    )
}
